### ISSUE TITLE
Game bugs out when attempting to display in fullscreen mode from startup.

### ISSUE THREAD

**Issue by Derpercoaster** [OpenLoco/OpenLoco#2009]
**Version information:**
 - Platform: Windows 10
 - Version: 23.06
 - Build/commit: a2207a48

**Describe the bug**
The game seems to struggle matching its internal resolution to the monitor resolution in full screen mode. I can't explain it really.
**To Reproduce**
Steps to reproduce the behaviour:
1. Set game to fullscreen mode
2. Quit and reload game
3. Observe as the game breaks.

**Expected behaviour**
I expect the game to not bug out and give me epilepsy when I start it.

**Screenshots**
https://github.com/OpenLoco/OpenLoco/assets/60452987/b794e3bd-158d-426d-be90-c95601707983

**Additional Information**
The video does not show what I see on the screen. When the black borders appear, the screen is going completely black for me, and when the mouse was moving around, I could see the game main menu, but nothing was clickable and the mouse was invisible. I think the only way to actually show what I see is to record my monitor with a phone camera or something similar.

**Comment by AaronVanGeffen** [comment]
I believe this bug has been fixed on master since the 23.06 release. Could you try a more recent build?

**Comment by Derpercoaster** [comment]
Seeing as all later builds crash on startup for me, I can't.

**Comment by AaronVanGeffen** [comment]
Do you mean the latest release (v23.06.1), or a 'master' build? For example, the one for commit [abb92c6](https://github.com/OpenLoco/OpenLoco/actions/runs/5348666692). You can find a Windows build at the bottom of the page.

**Comment by LeftofZen** [comment]
@Derpercoaster can you confirm you still have the problem on 23.06.1? or otherwise confirm fixed?
